print("Enter the given details: ")
name=input("Name ")
sap_id=input("Sap Id ")
add=input("Address ")
dep=input("Department ")
subject=input("Subject ")
print()
print("Your info. is")
print(name)
print(sap_id)
print(add)
print(dep)
print(subject)